OUTPUT_FOLDER: ENEO_output/
TEMP_DIR: temp_gatk
datadirs:
  BQSR: BQSR
  HLA_typing: HLA_typing
  VCF: VCF
  VCF_germ: VCF_germ
  VCF_out: VCF_out
  bams: bams
  expression: expression_data
  index_folder: genome_index
  logs:
    align: log/align
    annotate_variants: log/annotate_variants
    bam_cleaning: log/bam_cleaning
    bam_readcount: log/bam_readcount
    base_recalibration: log/base_recalibration
    decompose: log/decompose
    export_quant: log/export_quant
    intervals: log/intervals
    pMHC: log/pMHC
    salmon_quant: log/salmon_quant
    snv_calling: log/snv_calling
    sort_bam: log/sort_bam
    star_idx: log/star_idx
    t1k: log/t1k
    trimming: log/trimming
  mapped_reads: mapped_reads
  peptides: peptides
  salmon_idx: salmon_index
  salmon_quant: quantification
  trimmed_reads: trimmed_reads
  trimming_report: fastp_report
  utils: utils
params:
  BQSR:
    RAM: 30000
    extra: ''
    threads: 4
  MarkDuplicates:
    RAM: 30000
    extra: ''
    threads: 4
  STAR:
    RAM: null
    extra: '--twopassMode Basic --outSAMtype BAM Unsorted --readFilesCommand zcat '
    threads: 12
  SplitNCigarReads:
    RAM: 30000
    extra: ''
    threads: 4
  gatk:
    RAM: 20
    extra:
      RGPU: unit1
      RGSM: 20
  pMHC:
    threads: 4
  pvacseq:
    RAM: null
    extra: null
    threads: 2
  salmon:
    RAM: null
    extra:
      extra: --gcBias --seqBias --reduceGCMemory
      index: --keep-duplicates
      libtype: A
      zip_ext: gz
    threads: 8
  samtools:
    RAM: null
    extra: ''
    threads: 4
  strelka2:
    RAM: null
    extra: null
    threads: 8
  t1k:
    RAM: null
    extra: null
    threads: 8
  vcfanno:
    RAM: null
    extra: null
    threads: 8
  vep:
    RAM: null
    extra:
      assembly: GRCh38
      filtering: --gencode_basic --coding_only --no_intergenic
      plugins:
        Frameshift: workflow/utils/vep_plugins/Frameshift.pm
        Wildtype: workflow/utils/vep_plugins/Wildtype.pm
    threads: null
resources:
  cosmic: test_data/cosmic_chr6.vcf.gz
  dbsnps: null
  genome: null
  germline_prob_script: workflow/scripts/germProb.py
  giab_intervals: workflow/supplementary_res/GRCh38_giab_merged.bed.gz
  gnomad: null
  gsnps: null
  gtf: null
  hla_script: workflow/scripts/HLA_typing.py
  indel: null
  intervals_coding: workflow/supplementary_res/intervals_coding.BED.gz
  REDI: null
  t1k_file: workflow/supplementary_res/hlaidx_rna_seq.fa
  toml_script: workflow/scripts/createTOML.py
  transcriptome: null
  vep_cache: null
  vcfanno_binary: workflow/utils/vcfanno_linux64
  vcfanno_lua: workflow/utils/custom.lua
  vcfanno_toml: workflow/utils/vcfanno.toml
slurm_log_dir: slurm-logs
